import { getSession } from "@/helpers/session";
import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter from next/font/google
import { CN } from "../helpers/Cn";
import { Navbar } from "./components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getSession();

  return (
    <html lang="en">
      <body
        className={CN('bg-slate-890', inter.className)}
      >
        <Navbar user={user} />

        {children}
      </body>
    </html>
  );
}
